version: '3'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: test-1
  pgsql:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./docker/pgsql/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test-2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin